import type { CSSProperties } from 'react'
import { theme } from '../theme'

export const bookingConfirmationStyles: Record<string, CSSProperties> = {
  container: {
    maxWidth: '700px',
    margin: '0 auto',
    padding: theme.spacing.xl,
  },
  successCard: {
    backgroundColor: theme.colors.successBackground,
    border: `1px solid ${theme.colors.success}`,
    borderRadius: theme.radius.medium,
    padding: `${theme.spacing.xxxl} ${theme.spacing.xxl}`,
    textAlign: 'center',
    marginBottom: theme.spacing.xxl,
  } as CSSProperties,
  successIcon: {
    fontSize: '48px',
    color: theme.colors.success,
    marginBottom: theme.spacing.lg,
  },
  successTitle: {
    fontSize: '24px',
    fontWeight: '700',
    color: theme.colors.success,
    marginBottom: theme.spacing.sm,
  },
  successMessage: {
    fontSize: theme.typography.body.fontSize,
    color: theme.colors.success,
  },
  referenceCard: {
    backgroundColor: theme.colors.white,
    border: `2px solid ${theme.colors.primary}`,
    borderRadius: theme.radius.medium,
    padding: theme.spacing.xxl,
    textAlign: 'center',
    marginBottom: theme.spacing.xxl,
  } as CSSProperties,
  referenceLabel: {
    fontSize: theme.typography.labelSmall.fontSize,
    fontWeight: '600',
    color: theme.colors.textLight,
    textTransform: 'uppercase',
    marginBottom: theme.spacing.sm,
  },
  referenceNumber: {
    fontSize: '28px',
    fontWeight: '700',
    color: theme.colors.primary,
    fontFamily: 'monospace',
    marginBottom: theme.spacing.lg,
    letterSpacing: '2px',
  },
  copyButton: {
    padding: `${theme.spacing.sm} ${theme.spacing.xl}`,
    backgroundColor: theme.colors.primary,
    color: theme.colors.white,
    border: 'none',
    borderRadius: theme.radius.small,
    fontSize: theme.typography.body.fontSize,
    fontWeight: '600',
    cursor: 'pointer',
    transition: `background-color ${theme.transitions.normal}`,
  } as CSSProperties,
  detailsCard: {
    backgroundColor: theme.colors.white,
    border: `1px solid ${theme.colors.border}`,
    borderRadius: theme.radius.medium,
    padding: theme.spacing.xxl,
    marginBottom: theme.spacing.xxl,
  } as CSSProperties,
  detailsTitle: {
    fontSize: theme.typography.h3.fontSize,
    fontWeight: '600',
    marginBottom: theme.spacing.xl,
    color: theme.colors.text,
  },
  detailsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))',
    gap: theme.spacing.xxl,
  } as CSSProperties,
  section: {
    paddingBottom: theme.spacing.lg,
    borderBottom: `1px solid ${theme.colors.border}`,
  } as CSSProperties,
  sectionTitle: {
    fontSize: theme.typography.label.fontSize,
    fontWeight: '600',
    color: theme.colors.text,
    marginBottom: theme.spacing.md,
    textTransform: 'uppercase',
  },
  row: {
    display: 'flex',
    justifyContent: 'space-between',
    marginBottom: theme.spacing.sm,
    fontSize: theme.typography.body.fontSize,
  } as CSSProperties,
  label: {
    color: theme.colors.textLight,
    fontWeight: '500',
  },
  value: {
    color: theme.colors.text,
    textAlign: 'right',
  } as CSSProperties,
  confirmationTime: {
    textAlign: 'center',
    fontSize: theme.typography.bodySmall.fontSize,
    color: '#999',
    marginBottom: theme.spacing.xxl,
  } as CSSProperties,
  actions: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: theme.spacing.md,
  } as CSSProperties,
  primaryButton: {
    padding: theme.spacing.lg,
    backgroundColor: theme.colors.primary,
    color: theme.colors.white,
    border: 'none',
    borderRadius: theme.radius.small,
    fontSize: theme.typography.body.fontSize,
    fontWeight: '600',
    cursor: 'pointer',
    transition: `background-color ${theme.transitions.normal}`,
  } as CSSProperties,
  secondaryButton: {
    padding: theme.spacing.lg,
    backgroundColor: theme.colors.border,
    color: theme.colors.text,
    border: 'none',
    borderRadius: theme.radius.small,
    fontSize: theme.typography.body.fontSize,
    fontWeight: '600',
    cursor: 'pointer',
    transition: `background-color ${theme.transitions.normal}`,
  } as CSSProperties,
}
